// packages/svelte/src/direct-template.svelte
<script context="module" lang="ts">
  export type EmbedDirectTemplateProps = {
    className?: string;
    host?: string;
    token: string;
    externalId?: string; // @src: /apps/web/src/app/embed/direct/[[...url]]/schema

    css?: string | undefined;
    cssVars?: Record<string, string> | undefined;
    email?: string | undefined;
    lockEmail?: boolean | undefined;
    name?: string | undefined;
    lockName?: boolean | undefined;
    onDocumentReady?: () => void;
    onDocumentCompleted?: (data: {
      token: string;
      documentId: number;
      recipientId: number;
    }) => void;
    onDocumentError?: (error: string) => void;
    onFieldSigned?: () => void;
    onFieldUnsigned?: () => void;
  };
</script>

<script lang="ts">
  import { onDestroy, onMount } from "svelte";

  export let host: EmbedDirectTemplateProps["host"] = undefined;
  export let name: EmbedDirectTemplateProps["name"] = undefined;
  export let lockName: EmbedDirectTemplateProps["lockName"] = undefined;
  export let email: EmbedDirectTemplateProps["email"] = undefined;
  export let lockEmail: EmbedDirectTemplateProps["lockEmail"] = undefined;
  export let css: EmbedDirectTemplateProps["css"] = undefined;
  export let token: EmbedDirectTemplateProps["token"];
  export let externalId: EmbedDirectTemplateProps["externalId"] = undefined;
  export let onDocumentReady: EmbedDirectTemplateProps["onDocumentReady"] =
    undefined;
  export let onDocumentCompleted: EmbedDirectTemplateProps["onDocumentCompleted"] =
    undefined;
  export let onDocumentError: EmbedDirectTemplateProps["onDocumentError"] =
    undefined;
  export let onFieldSigned: EmbedDirectTemplateProps["onFieldSigned"] =
    undefined;
  export let onFieldUnsigned: EmbedDirectTemplateProps["onFieldUnsigned"] =
    undefined;
  export let className: EmbedDirectTemplateProps["className"] = undefined;

  function handleMessage(event: MessageEvent) {
    if (__iframe?.contentWindow === event.source) {
      switch (event.data.action) {
        case "document-ready":
          onDocumentReady?.();
          break;

        case "document-completed":
          onDocumentCompleted?.(event.data.data);
          break;

        case "document-error":
          onDocumentError?.(event.data.data);
          break;

        case "field-signed":
          onFieldSigned?.();
          break;

        case "field-unsigned":
          onFieldUnsigned?.();
          break;
      }
    }
  }
  $: src = () => {
    const appHost = host || "https://thewallet.ai";
    const encodedOptions = btoa(
      JSON.stringify({
        name: name,
        lockName: lockName,
        email: email,
        lockEmail: lockEmail,
        css: css,
      })
    );
    const srcUrl = new URL(`/embed/direct/${token}`, appHost);

    if (externalId) {
      srcUrl.searchParams.set("externalId", externalId);
    }

    return `${srcUrl}#${encodedOptions}`;
  };

  let __iframe;

  onMount(() => {
    window.addEventListener("message", handleMessage);
  });

  onDestroy(() => {
    window.removeEventListener("message", handleMessage);
  });
</script>

<iframe bind:this={__iframe} class={className} src={src()} />

// packages/solid/src/direct-template.tsx
import { onMount, createSignal, createMemo } from "solid-js";

export type EmbedDirectTemplateProps = {
  className?: string;
  host?: string;
  token: string;
  externalId?: string; // @src: /apps/web/src/app/embed/direct/[[...url]]/schema

  css?: string | undefined;
  cssVars?: Record<string, string> | undefined;
  email?: string | undefined;
  lockEmail?: boolean | undefined;
  name?: string | undefined;
  lockName?: boolean | undefined;
  onDocumentReady?: () => void;
  onDocumentCompleted?: (data: {
    token: string;
    documentId: number;
    recipientId: number;
  }) => void;
  onDocumentError?: (error: string) => void;
  onFieldSigned?: () => void;
  onFieldUnsigned?: () => void;
};

function EmbedDirectTemplate(props: EmbedDirectTemplateProps) {
  const src = createMemo(() => {
    const appHost = props.host || "https://thewallet.ai";
    const encodedOptions = btoa(
      JSON.stringify({
        name: props.name,
        lockName: props.lockName,
        email: props.email,
        lockEmail: props.lockEmail,
        css: props.css,
      })
    );
    const srcUrl = new URL(`/embed/direct/${props.token}`, appHost);

    if (props.externalId) {
      srcUrl.searchParams.set("externalId", props.externalId);
    }

    return `${srcUrl}#${encodedOptions}`;
  });

  function handleMessage(event: MessageEvent) {
    if (__iframe?.contentWindow === event.source) {
      switch (event.data.action) {
        case "document-ready":
          props.onDocumentReady?.();
          break;

        case "document-completed":
          props.onDocumentCompleted?.(event.data.data);
          break;

        case "document-error":
          props.onDocumentError?.(event.data.data);
          break;

        case "field-signed":
          props.onFieldSigned?.();
          break;

        case "field-unsigned":
          props.onFieldUnsigned?.();
          break;
      }
    }
  }

  let __iframe: HTMLIFrameElement;

  onMount(() => {
    window.addEventListener("message", handleMessage);
  });

  return (
    <>
      <iframe class={props.className} ref={__iframe!} src={src()}></iframe>
    </>
  );
}

export default EmbedDirectTemplate;
